version: '3.4'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
    environment:
      - BUILDKITE_PLUGIN_DOCKER_ECR_CACHE_ECR_TAGS_MYKEY=mykeyvalue
      - BUILDKITE_PLUGIN_DOCKER_ECR_CACHE_ECR_TAGS_MYKEY2=mykeyvalue2
  lint:
    image: buildkite/plugin-linter
    command: ['--name', 'seek-oss/docker-ecr-cache']
    volumes:
      - ".:/plugin:ro"

